package pl.michalschielmann.adventofcode.y2021;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Day2DivePuzzleTest {

    @Test
    public void forTestInput_expectedDistanceOnXAxis_is15() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(TEST_INPUT);

        int distanceOnXAxis = puzzle.getDistanceOnXAxis();

        assertEquals(15, distanceOnXAxis);
    }

    @Test
    public void forTestInput_expectedIncreaseInDepth_is10() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(TEST_INPUT);

        int increaseInDepth = puzzle.getIncreaseInDepth();

        assertEquals(10, increaseInDepth);
    }

    @Test
    public void forTestInput_expectedDistanceMetric_is150() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(TEST_INPUT);

        int increaseInDepth = puzzle.getDistanceMetric();

        assertEquals(150, increaseInDepth);
    }

    @Test
    public void acceptanceTestForDistanceMetricUsingDepthAndDistance() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(INPUT);

        int increaseInDepth = puzzle.getDistanceMetric();

        assertEquals(1924923, increaseInDepth);
    }

    @Test
    public void forTestInput_distanceMetricUsingAim_is900() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(TEST_INPUT);

        int distance = puzzle.getDistanceMetricUsingAim();

        assertEquals(900, distance);
    }

    @Test
    public void acceptanceTestForCalculatingDistanceUsingAimX() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(INPUT);

        int distance = puzzle.getDistanceMetricUsingAim();

        assertEquals(1982495697, distance);
    }

    @Test
    public void acceptsNotFormattedInput() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(NOT_FORMATTED_INPUT);

        int distanceOnXAxis = puzzle.getDistanceOnXAxis();

        assertEquals(15, distanceOnXAxis);
    }

    @Test
    public void acceptsInputWithMissingLine() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle(EMPTY_LINE_INPUT);

        int distanceOnXAxis = puzzle.getDistanceOnXAxis();

        assertEquals(15, distanceOnXAxis);
    }

    @Test
    public void acceptsEmptyInput() {
        Day2DivePuzzle puzzle = new Day2DivePuzzle("");

        int distanceOnXAxis = puzzle.getDistanceOnXAxis();

        assertEquals(0, distanceOnXAxis);
    }

    @Test
    public void throwsExceptionOnInputWithInvalidCommand() {
        assertThrows(IllegalArgumentException.class, () -> new Day2DivePuzzle(INVALID_COMMAND_INPUT));
    }

    @Test
    public void throwsExceptionOnInputWithInvalidDistance() {
        assertThrows(NumberFormatException.class, () -> new Day2DivePuzzle(INVALID_DISTANCE_INPUT));
    }

    private static final String TEST_INPUT = """
            forward 5
            down 5
            forward 8
            up 3
            down 8
            forward 2
            """;

    @SuppressWarnings("TrailingWhitespacesInTextBlock")
    private static final String NOT_FORMATTED_INPUT = """
            forward 5 
            down 5
             forward 8
            up 3
            down 8
            forward 2
            """;

    private static final String EMPTY_LINE_INPUT = """
            forward 5
                        
            forward 8
            up 3
            down 8
            forward 2
            """;

    private static final String INVALID_COMMAND_INPUT = """
            forward 5
            down 5
            invalid 8
            up 3
            down 8
            forward 2
            """;

    private static final String INVALID_DISTANCE_INPUT = """
            forward 5
            down invalid
            invalid 8
            up 3
            down 8
            forward 2
            """;

    private static final String INPUT = """
            forward 3
            down 6
            forward 7
            down 4
            down 8
            down 6
            down 4
            down 6
            forward 7
            down 5
            forward 1
            up 7
            up 6
            down 1
            down 2
            forward 3
            forward 3
            forward 4
            up 9
            up 4
            forward 9
            down 2
            down 6
            forward 1
            forward 8
            down 2
            up 5
            forward 3
            down 5
            forward 2
            forward 4
            down 2
            up 3
            up 6
            down 2
            down 2
            down 8
            forward 6
            up 3
            down 1
            forward 4
            forward 7
            up 8
            forward 8
            down 6
            down 3
            forward 9
            up 9
            forward 1
            forward 7
            down 8
            forward 8
            forward 2
            forward 5
            down 2
            forward 3
            forward 1
            forward 3
            forward 6
            forward 9
            up 3
            down 6
            down 9
            down 4
            down 6
            forward 2
            forward 8
            up 8
            down 9
            down 1
            down 8
            down 7
            forward 8
            forward 5
            down 5
            up 9
            up 9
            forward 2
            up 4
            forward 4
            up 4
            up 3
            up 3
            up 4
            down 7
            down 9
            down 9
            forward 6
            forward 4
            down 9
            down 2
            down 2
            down 1
            down 8
            down 3
            up 2
            down 3
            down 6
            down 5
            up 7
            forward 3
            forward 3
            forward 2
            forward 5
            forward 6
            down 7
            up 9
            down 9
            up 2
            up 8
            forward 2
            down 1
            up 7
            down 8
            up 1
            up 2
            up 1
            up 1
            forward 1
            down 8
            up 4
            up 5
            forward 5
            up 1
            down 8
            up 5
            down 6
            forward 8
            up 4
            forward 7
            down 9
            up 2
            forward 2
            down 6
            down 4
            up 2
            forward 9
            down 9
            forward 9
            down 5
            down 9
            forward 5
            up 8
            up 6
            down 4
            forward 3
            forward 7
            forward 6
            up 6
            down 1
            forward 9
            up 5
            down 2
            down 1
            forward 6
            down 9
            up 7
            up 3
            down 9
            down 5
            up 3
            forward 6
            up 6
            up 4
            down 3
            down 4
            down 6
            down 6
            up 7
            forward 1
            forward 6
            up 5
            up 2
            forward 7
            down 6
            up 1
            up 3
            forward 6
            up 8
            down 8
            down 7
            down 9
            forward 3
            forward 7
            forward 5
            forward 1
            down 7
            forward 6
            down 7
            up 3
            down 9
            down 7
            down 1
            forward 9
            forward 9
            forward 3
            down 9
            down 3
            forward 8
            down 4
            up 4
            up 6
            up 5
            up 2
            up 6
            forward 1
            down 1
            down 5
            up 7
            down 4
            up 2
            up 4
            down 1
            down 7
            down 9
            up 1
            down 1
            down 3
            forward 3
            forward 9
            forward 5
            down 1
            down 7
            down 9
            down 9
            down 6
            down 5
            forward 4
            down 8
            down 2
            down 9
            forward 2
            forward 2
            forward 6
            up 2
            forward 6
            forward 2
            down 6
            forward 7
            forward 8
            down 7
            up 7
            down 5
            up 7
            down 2
            down 6
            up 1
            down 2
            down 6
            forward 3
            down 9
            down 3
            forward 6
            up 7
            down 9
            down 7
            down 3
            down 6
            forward 5
            forward 9
            down 3
            down 6
            down 3
            down 8
            forward 9
            down 8
            down 4
            down 6
            up 8
            forward 3
            forward 3
            down 2
            down 1
            forward 3
            down 8
            down 2
            forward 4
            down 2
            forward 5
            down 8
            down 5
            forward 4
            down 6
            forward 3
            forward 4
            up 5
            up 5
            down 8
            down 1
            up 5
            down 7
            up 3
            forward 5
            forward 1
            forward 7
            forward 6
            down 5
            down 9
            down 5
            down 9
            down 6
            down 4
            down 7
            down 5
            down 9
            up 4
            down 2
            down 4
            up 6
            forward 8
            forward 9
            up 4
            down 6
            down 1
            forward 6
            forward 1
            forward 6
            down 9
            forward 9
            down 8
            up 9
            down 5
            forward 1
            forward 5
            down 7
            forward 2
            forward 3
            down 1
            down 1
            up 9
            down 7
            down 6
            forward 4
            down 9
            forward 8
            up 7
            forward 2
            forward 7
            forward 2
            down 5
            down 8
            down 7
            down 4
            up 7
            down 6
            up 5
            up 1
            down 2
            forward 2
            forward 4
            down 3
            down 2
            down 5
            forward 7
            forward 1
            forward 7
            forward 3
            forward 2
            forward 8
            up 3
            down 2
            forward 6
            down 6
            up 2
            down 4
            forward 8
            forward 6
            up 7
            down 9
            forward 7
            down 8
            up 3
            down 5
            forward 7
            forward 5
            forward 4
            up 9
            down 1
            down 7
            forward 1
            forward 8
            forward 2
            forward 2
            forward 2
            up 8
            up 4
            down 7
            forward 3
            forward 7
            up 4
            forward 4
            down 1
            forward 9
            forward 3
            up 2
            forward 3
            down 1
            down 7
            up 8
            up 5
            up 2
            forward 9
            up 6
            forward 2
            forward 4
            forward 6
            down 4
            forward 6
            down 6
            down 2
            down 1
            up 5
            down 3
            forward 4
            down 5
            forward 3
            up 6
            down 1
            down 3
            up 3
            forward 7
            down 8
            forward 8
            forward 2
            down 2
            up 6
            down 7
            forward 6
            forward 7
            forward 3
            down 1
            forward 9
            down 7
            forward 8
            forward 3
            forward 1
            forward 1
            down 1
            up 4
            forward 9
            down 1
            down 1
            down 5
            forward 9
            forward 4
            forward 9
            down 3
            down 7
            down 9
            up 1
            up 1
            up 8
            forward 3
            down 8
            forward 8
            up 5
            up 4
            down 5
            down 6
            forward 5
            down 4
            forward 7
            down 7
            forward 2
            down 4
            forward 6
            down 7
            down 7
            down 4
            forward 1
            forward 4
            down 7
            up 4
            down 3
            forward 8
            forward 5
            down 2
            up 9
            down 9
            up 2
            down 6
            down 4
            forward 6
            down 4
            up 4
            up 7
            up 2
            down 8
            up 3
            down 9
            up 6
            down 2
            forward 6
            down 2
            forward 8
            forward 2
            forward 5
            up 3
            down 7
            down 1
            forward 8
            down 9
            forward 5
            up 9
            forward 7
            up 3
            up 2
            down 9
            down 1
            forward 1
            forward 3
            forward 2
            forward 2
            forward 7
            up 6
            forward 5
            up 3
            up 7
            down 7
            forward 7
            forward 1
            down 1
            up 3
            up 6
            down 5
            up 1
            down 5
            down 2
            down 3
            up 7
            up 6
            up 9
            down 9
            forward 4
            up 7
            forward 3
            down 7
            up 3
            forward 1
            down 7
            forward 5
            up 9
            up 9
            down 6
            forward 2
            up 5
            forward 5
            down 2
            forward 6
            down 4
            up 1
            forward 1
            down 1
            up 2
            down 4
            down 3
            forward 7
            up 3
            down 8
            forward 9
            up 8
            down 7
            down 6
            up 6
            forward 5
            up 8
            down 1
            down 4
            up 3
            forward 2
            up 5
            down 1
            forward 1
            forward 7
            down 3
            down 2
            forward 8
            down 4
            down 3
            down 6
            forward 8
            down 3
            up 2
            down 4
            up 7
            forward 9
            up 2
            up 6
            down 1
            down 5
            up 9
            forward 6
            up 7
            forward 8
            down 7
            up 1
            forward 7
            up 2
            forward 4
            forward 1
            down 7
            down 5
            forward 3
            forward 6
            up 3
            up 1
            forward 8
            forward 4
            down 8
            down 2
            down 6
            down 2
            down 9
            down 7
            down 3
            down 3
            down 9
            up 8
            forward 1
            down 5
            up 4
            forward 6
            up 5
            up 9
            down 9
            up 5
            up 9
            forward 8
            up 4
            forward 3
            down 3
            forward 4
            down 8
            down 8
            forward 8
            down 1
            forward 8
            down 2
            forward 7
            up 1
            forward 6
            down 8
            up 1
            down 6
            down 1
            forward 3
            forward 3
            down 7
            up 6
            up 2
            down 9
            up 5
            forward 6
            down 3
            down 8
            forward 6
            down 7
            down 5
            forward 9
            down 5
            forward 4
            down 7
            forward 5
            down 6
            down 3
            down 9
            down 8
            down 1
            forward 4
            down 9
            up 4
            down 3
            down 8
            forward 5
            forward 9
            up 7
            up 5
            up 5
            up 8
            down 6
            up 7
            forward 7
            forward 4
            down 6
            forward 6
            up 4
            down 7
            down 2
            forward 6
            down 9
            down 1
            forward 3
            forward 9
            forward 8
            down 4
            forward 6
            forward 6
            forward 7
            down 8
            down 8
            forward 6
            down 9
            forward 9
            down 7
            down 5
            down 8
            forward 6
            down 5
            forward 9
            down 6
            forward 9
            forward 4
            forward 1
            up 4
            forward 5
            down 6
            forward 8
            forward 3
            up 3
            up 2
            up 7
            forward 3
            up 3
            forward 4
            forward 3
            up 4
            up 1
            down 9
            forward 8
            down 7
            down 2
            down 4
            up 6
            forward 6
            down 6
            up 7
            forward 4
            down 4
            forward 7
            forward 6
            down 9
            down 1
            up 3
            forward 2
            up 2
            down 9
            forward 6
            forward 8
            down 8
            down 5
            forward 2
            forward 6
            forward 9
            forward 9
            down 5
            up 4
            down 6
            forward 7
            forward 9
            up 6
            forward 4
            up 7
            forward 7
            down 4
            forward 7
            forward 4
            up 5
            forward 6
            down 2
            down 3
            up 2
            forward 4
            forward 8
            up 5
            up 7
            down 9
            forward 2
            forward 9
            forward 8
            forward 5
            down 5
            down 8
            down 3
            up 9
            down 2
            down 6
            up 4
            forward 8
            forward 8
            up 6
            forward 8
            down 3
            forward 3
            up 7
            forward 2
            down 8
            forward 8
            forward 6
            forward 3
            up 2
            forward 8
            forward 5
            down 9
            up 1
            down 3
            down 1
            up 5
            up 7
            up 8
            down 9
            forward 4
            forward 1
            down 6
            forward 8
            forward 8
            forward 4
            down 7
            down 8
            forward 5
            down 2
            forward 5
            forward 9
            down 7
            down 8
            forward 5
            down 1
            down 7
            down 4
            forward 2
            down 1
            forward 7
            up 1
            up 7
            forward 4
            forward 2
            forward 3
            forward 5
            forward 7
            up 3
            down 1
            down 9
            forward 8
            forward 9
            forward 5
            up 3
            down 5
            forward 4
            down 9
            forward 1
            forward 4
            up 3
            forward 4
            down 9
            up 9
            down 3
            forward 1
            forward 9
            up 8
            forward 4
            up 2
            down 1
            down 5
            down 4
            down 3
            forward 4
            forward 9
            forward 1
            up 6
            down 1
            down 3
            forward 8
            forward 3
            down 6
            forward 2
            down 6
            down 2
            forward 4
            forward 7
            forward 4
            up 4
            up 8
            up 7
            up 9
            forward 3
            forward 1
            down 9
            down 5
            forward 6
            forward 6
            forward 2
            down 8
            down 4
            down 2
            down 7
            up 2
            forward 7
            forward 5
            forward 5
            forward 1
            down 9
            forward 3
            forward 3
            down 8
            forward 3
            down 5
            down 2
            forward 3
            up 3
            forward 5
            down 8
            forward 6
            forward 6
            forward 9
            forward 9
            forward 8
            forward 4
            forward 6
            forward 6
            up 7
            down 6
            down 6
            forward 6
            up 5
            forward 6
            down 8
            down 5
            down 8
            down 8
            up 5
            down 2
            forward 4
            down 2
            up 6
            down 8
            down 4
            up 3
            up 2
            down 1
            forward 2
            forward 6
            down 7
            forward 7
            down 6
            down 2
            down 3
            down 6
            forward 4
            up 1
            forward 7
            down 4
            forward 8
            forward 9
            forward 6
            down 1
            forward 8
            down 7
            up 9
            down 5
            forward 4
            forward 3
            down 8
            down 5
            down 4
            forward 7
            down 9
            down 2
            forward 3
            down 7
            up 1
            forward 4
            down 3
            up 4
            down 2
            down 7
            down 1
            down 3
            forward 5
            forward 5
            down 2
            up 2
            down 8
            forward 8
            down 5
            forward 9
            down 5
            forward 6
            forward 9
            forward 3
            down 5
            down 2
            down 8
            up 9
            up 8
            down 8
            forward 4
            up 5
            forward 1
            up 4
            down 1
            forward 2
            """;
}
